### ISSUE TITLE
Wifi device needed

### ISSUE THREAD

**Issue by solution22llc** [openbouffalo/buildroot_bouffalo#10]
Any chance you all could add a wifi device so the board can connect to the internet?

**Comment by Fishwaldo** [comment]
When bouffalo release details about the Wifi/BT peripheral on the bl808 we will explore. Currently that information is not available.

**Comment by solution22llc** [comment]
Thank you!

**Comment by D1plo1d** [comment]
@Fishwaldo have there been any indications that Buffalo Labs might release that information? I've been trying to google this for more info but so far all I've been able to find is people saying that the wifi info is under NDA and not able to be released by Buffalo Labs.

**Comment by gamelaster** [comment]
@D1plo1d wifi library will be released, hopefully soon (we don't know exact date yet). Although it will be in form of library file (blob), as everything around wifi is under NDA.

**Comment by leow149** [comment]
Any updates on this? Or where can I check myself?

**Comment by gamelaster** [comment]
@leow149 still nothing

**Comment by gamelaster** [comment]
@kvtb so far nobody tried to get it working.

**Comment by maks** [comment]
Not sure I follow all this, but I wonder if this implies its the same wifi part as on the bl602's ? https://github.com/sipeed/M1s_BL808_SDK/tree/6eeb195f639d828d41dd997c83392e59ae231668/components/network/wifi_manager/bl60x_wifi_driver

**Comment by gamelaster** [comment]
@maks most likely no, just left over from the SDK

**Comment by gamelaster** [comment]
Bouffalo is working on WiFi support, some people got it running. Check out Bouffalo's official repos, eventually their effort should be merged also here.
