### ISSUE TITLE
Devcube error when trying to flash M0 and D0

### ISSUE THREAD

**Issue by pietgeursen** [openbouffalo/buildroot_bouffalo#42]
Hi there,
I'm trying to follow the instructions to get a pine 0x64 running. I'm getting this error in devcube when trying to flash M0 and D0:
```
pt check fail, chips/bl808/img_create_mcu/bootinfo_group1.bin is overlayed with chips/bl808/img_create_mcu/img_group0.bin in flash layout, please check your partition table to fix this issue
```
<img width="1333" alt="Screen Shot 2023-03-04 at 7 56 25 PM" src="https://user-images.githubusercontent.com/10556538/222881089-0892d857-1d01-43ee-94d0-f8683e1f2c67.png">

I'm using v1.0.0 release, full_defconfig.
Devcube version 1.8.3, downloaded today.

Am I doing something silly?

**Comment by Fishwaldo** [comment]
You need to set D0 to group0

**Comment by pietgeursen** [comment]
Ooof, you are so right! Thanks so much for replying :)
