### ISSUE TITLE
SPI tft

### ISSUE THREAD

**Issue by KTechDev4213** [openbouffalo/buildroot_bouffalo#65]
Is there a tft driver.

**Comment by eeucalyptus** [comment]
Unfortunately no. 

Actually there is always [fbtft](https://github.com/notro/fbtft), which can be used off-the-shelf, but it requires SPI, which has not yet been implemented in the [kernel](https://github.com/openbouffalo/linux)... There was even some bounty two months ago. Also with the goal of using a tft, but I haven't heard of someone actually implementing it.

**Comment by gamelaster** [comment]
Not yet, and generally, there is no SPI driver, (yet). I will close the issue for now.
