### ISSUE TITLE
Mount root with a PartUUID

### ISSUE THREAD

**Issue by Fishwaldo** [openbouffalo/buildroot_bouffalo#7]
Instead of hardcoded device path.

http://lists.busybox.net/pipermail/buildroot/2017-June/194458.html

**Comment by gamelaster** [comment]
Also, some of Buildroot configs moved to use PARTLABEL instead.

**Comment by Fishwaldo** [comment]
PARTLABEL requires a initramfs as the kernel itself can't resolve labels, only Partition UUID's. With the limited ram, not sure we want to go that path? (Although it would be nice!)

**Comment by gamelaster** [comment]
PARTLABEL doesn't require initramfs. The FSLABEL does.
Since Linux can read PARTUUID, it can resolve PARTLABEL. But it can't resolve FSUUID and FSLABEL.
